// SPDX-License-Identifier: Apache-2.0
//
// neural_osc: Neural MORPHING oscillator voice engine (voice 7).
//
//   A small fixed-point MLP whose `morph` control sweeps the output timbre
//   across a waveshape continuum (sine -> saw -> square -> pulse). Each
//   sample_tick advances a phase accumulator; from the phase we build a 5-element
//   feature vector -- the first four sine harmonics from a quantized LUT plus the
//   scaled morph -- and run it through a 5 -> 8 -> 8 -> 1 MLP (ReLU hidden layers,
//   linear output) to produce one signed-16 audio sample.
//
//   This is a BIT-EXACT integer datapath. The arithmetic (sine LUT, feature
//   build, layer MACs, Q1.14 requant shifts, ReLU, output scale + signed-16
//   clamp) mirrors models/neural_ref.py operation-for-operation, and the trained
//   constants come from models/neural_weights.hex (written by neural_train.py).
//   Read both before touching the math here.
//
//   Engine contract (NOTES.md): active-low SYNCHRONOUS reset; state advances only
//   on sample_tick; `sample` is registered and stable between ticks. The MLP is
//   time-shared over a single MAC, taking many clk cycles AFTER a tick to finish,
//   but `sample` is valid well before the next tick (the TB gives a large budget).
//
//   Memory image (baked into the RTL via `include "neural_weights_init.svh",
//   which models/neural_train.py GENERATES from the same constants it writes to
//   models/neural_weights.hex -- bit-for-bit identical, but with NO runtime file
//   dependency, so the build is synthesis-safe):
//     mem[0 .. 255]    : sine LUT (signed Q1.14)
//     mem[256 .. 384]  : 129 MLP weight/bias words, in consumption order
//                        L1: 8 * (5 weights + 1 bias)
//                        L2: 8 * (8 weights + 1 bias)
//                        L3: 1 * (8 weights + 1 bias)
//   SPI overwrite: w_we writes mem[WEIGHT_BASE + w_addr] (first 64 weight words
//   reachable via the 6-bit w_addr; reset defaults already load ALL of them).

`timescale 1ns/1ps
`default_nettype none

module neural_osc #(
    parameter SAMPLE_W   = 16,
    parameter QBITS      = 14,            // Q1.14 fractional bits
    parameter LUT_DEPTH  = 256,           // sine LUT entries
    parameter PHASE_W    = 16,            // phase accumulator width
    parameter N_IN       = 5,             // MLP input features
    parameter H1         = 8,             // hidden layer 1 width
    parameter H2         = 8,             // hidden layer 2 width
    parameter N_OUT      = 1,             // output neurons
    parameter OUT_SHIFT  = 1,             // output Q1.14 << OUT_SHIFT -> signed-16
    parameter WEIGHT_BASE = 256,          // weights begin after the LUT
    parameter N_WEIGHTS  = 129,           // total weight/bias words
    parameter MEM_WORDS  = 385,           // LUT_DEPTH + N_WEIGHTS
    parameter WFILE      = "models/neural_weights.hex" // reference only; init is baked, see below
)(
    input  wire clk,
    input  wire rst_n,                                // active low, synchronous

    input  wire sample_tick,                          // audio-rate strobe
    input  wire [9:0] pitch,                          // phase increment per tick
    input  wire [7:0] morph,                          // morph amount (config 0x15[7:0])

    input  wire        w_we,                          // weight write strobe (1 clk)
    input  wire [5:0]  w_addr,                         // weight index (config 0x40-0x4F slice)
    input  wire [15:0] w_wdata,

    output reg  signed [SAMPLE_W-1:0] sample           // registered, held between ticks
);

    localparam LUT_SHIFT = PHASE_W - 8;               // top 8 phase bits index 256-entry LUT
    localparam signed [31:0] QSCALE = 32'sd1 <<< QBITS;  // 16384

    // ---------------------------------------------------------------------
    // Combined memory: sine LUT then MLP weights. The power-on/reset-default
    // contents are BAKED into the RTL by the generated include below (an
    // `initial` block of mem[i] = 16'h.... assignments) instead of a runtime
    // $readmemh -- the file path of $readmemh resolves at sim time (cwd=repo
    // root) but FAILS under a synthesis/hardening run dir, whereas baked init
    // values are honored by both iverilog (initial block) and yosys (init attr
    // on the reg). `mem` stays a writable reg so the w_we SPI port can overwrite
    // weight words at runtime. The include's values are bit-for-bit identical to
    // models/neural_weights.hex; both are generated by models/neural_train.py.
    // iverilog resolves the include relative to this file's dir (src/), so the
    // file lives in src/ alongside this module.
    // ---------------------------------------------------------------------
    reg signed [15:0] mem [0:MEM_WORDS-1];
    `include "neural_weights_init.svh"

    // ---------------------------------------------------------------------
    // Phase accumulator + the captured morph for the in-flight sample.
    // ---------------------------------------------------------------------
    reg [PHASE_W-1:0] phase;
    reg [7:0]         morph_q;

    // ---------------------------------------------------------------------
    // Activation register file. `act` holds the current layer's INPUTS,
    // `nxt` accumulates the current layer's OUTPUTS. Widths cover the largest
    // layer (8). Values are signed Q1.14 (fit in 16 bits; carried in 32 for
    // headroom during ReLU/requant).
    // ---------------------------------------------------------------------
    reg signed [31:0] act [0:7];
    reg signed [31:0] nxt [0:7];

    // ---------------------------------------------------------------------
    // FSM state.
    // ---------------------------------------------------------------------
    localparam [2:0] S_IDLE  = 3'd0,
                     S_FEAT  = 3'd1,   // build the 5 input features
                     S_MAC   = 3'd2,   // multiply-accumulate one (neuron,input)
                     S_NEURON= 3'd3,   // finish a neuron: +bias, requant, ReLU, store
                     S_LDONE = 3'd4,   // finish a layer: copy nxt->act, advance layer
                     S_OUT   = 3'd5;   // scale + clamp output neuron -> sample

    reg [2:0]  state;
    reg [1:0]  layer;                 // 0=L1, 1=L2, 2=L3
    reg [3:0]  neuron;                // output neuron index within the layer
    reg [3:0]  in_idx;                // input index within the neuron
    reg [3:0]  feat_idx;             // feature build counter (0..N_IN-1)
    reg [9:0]  wptr;                  // running pointer into the weights region
    reg signed [47:0] acc;            // wide MAC accumulator

    // current-layer geometry (combinational from `layer`)
    reg [3:0] cur_nin;
    reg [3:0] cur_nout;
    reg       cur_relu;
    always @(*) begin
        case (layer)
            2'd0:    begin cur_nin = N_IN[3:0]; cur_nout = H1[3:0];    cur_relu = 1'b1; end
            2'd1:    begin cur_nin = H1[3:0];   cur_nout = H2[3:0];    cur_relu = 1'b1; end
            default: begin cur_nin = H2[3:0];   cur_nout = N_OUT[3:0]; cur_relu = 1'b0; end
        endcase
    end

    // ---------------------------------------------------------------------
    // Sine LUT lookup for harmonic `h` (1..4): index = top 8 bits of
    // (h * phase) mod 2^PHASE_W. The multiply is done at full width then masked.
    // ---------------------------------------------------------------------
    function automatic [PHASE_W-1:0] harm_phase(input [2:0] h);
        reg [PHASE_W+2:0] prod;
        begin
            prod = phase * h;                       // up to 4*phase, wraps mod 2^PHASE_W
            harm_phase = prod[PHASE_W-1:0];
        end
    endfunction

    function automatic [7:0] lut_index(input [2:0] h);
        reg [PHASE_W-1:0] hp;
        begin
            hp = harm_phase(h);
            lut_index = hp[PHASE_W-1 -: 8];          // top 8 bits
        end
    endfunction

    // morph mapped to Q1.14 [-16384, 16256]:  (morph << 7) - QSCALE
    wire signed [31:0] morph_feat =
        $signed({1'b0, morph_q, 7'b0}) - QSCALE;     // morph_q*128 - 16384

    // requant: acc (product scale Q2.28) + bias<<QBITS, then >>> QBITS -> Q1.14
    // computed in S_NEURON.

    integer ii;
    always @(posedge clk) begin
        if (!rst_n) begin
            phase    <= {PHASE_W{1'b0}};
            morph_q  <= 8'd0;
            sample   <= {SAMPLE_W{1'b0}};
            state    <= S_IDLE;
            layer    <= 2'd0;
            neuron   <= 4'd0;
            in_idx   <= 4'd0;
            feat_idx <= 4'd0;
            wptr     <= 10'd0;
            acc      <= 48'sd0;
            for (ii = 0; ii < 8; ii = ii + 1) begin
                act[ii] <= 32'sd0;
                nxt[ii] <= 32'sd0;
            end
        end else if (w_we) begin
            // SPI weight overwrite. Reachable range is the first 64 weight words
            // via the 6-bit w_addr; reset defaults already load all of them.
            mem[WEIGHT_BASE + w_addr] <= $signed(w_wdata);
        end else begin
            case (state)
                // ---- wait for an audio tick ----------------------------------
                S_IDLE: begin
                    if (sample_tick) begin
                        phase    <= phase + {{(PHASE_W-10){1'b0}}, pitch};
                        morph_q  <= morph;
                        layer    <= 2'd0;
                        neuron   <= 4'd0;
                        in_idx   <= 4'd0;
                        feat_idx <= 4'd0;
                        wptr     <= 10'd0;
                        acc      <= 48'sd0;
                        state    <= S_FEAT;
                    end
                end

                // ---- build the 5 input features into act[0..4] ---------------
                // Uses the UPDATED phase/morph_q (registered on the tick above;
                // available from the next clk, which is when S_FEAT runs).
                S_FEAT: begin
                    case (feat_idx)
                        4'd0: act[0] <= $signed(mem[lut_index(3'd1)]);
                        4'd1: act[1] <= $signed(mem[lut_index(3'd2)]);
                        4'd2: act[2] <= $signed(mem[lut_index(3'd3)]);
                        4'd3: act[3] <= $signed(mem[lut_index(3'd4)]);
                        default: act[4] <= morph_feat;
                    endcase
                    if (feat_idx == N_IN[3:0] - 1) begin
                        feat_idx <= 4'd0;
                        state    <= S_MAC;
                        acc      <= 48'sd0;
                    end else begin
                        feat_idx <= feat_idx + 4'd1;
                    end
                end

                // ---- MAC: acc += act[in_idx] * weight; advance input ---------
                S_MAC: begin
                    acc  <= acc + $signed(act[in_idx]) * $signed(mem[WEIGHT_BASE[9:0] + wptr]);
                    wptr <= wptr + 10'd1;
                    if (in_idx == cur_nin - 4'd1) begin
                        in_idx <= 4'd0;
                        state  <= S_NEURON;
                    end else begin
                        in_idx <= in_idx + 4'd1;
                    end
                end

                // ---- finish a neuron: + bias, requant >>> QBITS, ReLU, store -
                S_NEURON: begin
                    // wptr now points at the bias word for this neuron.
                    // bias is Q1.14; lift to product scale (<<QBITS), add, requant.
                    nxt[neuron] <= relu_requant(
                        acc + ($signed(mem[WEIGHT_BASE[9:0] + wptr]) <<< QBITS),
                        cur_relu);
                    wptr <= wptr + 10'd1;               // consume the bias word
                    acc  <= 48'sd0;
                    if (neuron == cur_nout - 4'd1) begin
                        neuron <= 4'd0;
                        state  <= S_LDONE;
                    end else begin
                        neuron <= neuron + 4'd1;
                        state  <= S_MAC;                // next neuron's MAC
                    end
                end

                // ---- finish a layer: nxt -> act, advance layer or go to OUT --
                S_LDONE: begin
                    for (ii = 0; ii < 8; ii = ii + 1)
                        act[ii] <= nxt[ii];
                    if (layer == 2'd2) begin
                        state <= S_OUT;
                    end else begin
                        layer  <= layer + 2'd1;
                        neuron <= 4'd0;
                        in_idx <= 4'd0;
                        acc    <= 48'sd0;
                        state  <= S_MAC;
                    end
                end

                // ---- output neuron: scale Q1.14 << OUT_SHIFT, clamp signed-16 -
                S_OUT: begin
                    sample <= clamp_s16(act[0] <<< OUT_SHIFT);
                    state  <= S_IDLE;
                end

                default: state <= S_IDLE;
            endcase
        end
    end

    // ReLU + requant: shift the (products + lifted bias) accumulator back to
    // Q1.14 with an arithmetic right shift (floors toward -inf == Python >>),
    // then optional ReLU. Returned as a 32-bit signed Q1.14.
    function automatic signed [31:0] relu_requant(input signed [47:0] a,
                                                  input rl);
        reg signed [47:0] sh;
        begin
            sh = a >>> QBITS;                 // back to Q1.14, truncating
            if (rl && sh < 0)
                relu_requant = 32'sd0;
            else
                relu_requant = sh[31:0];
        end
    endfunction

    // Saturating clamp to signed-16.
    function automatic signed [SAMPLE_W-1:0] clamp_s16(input signed [31:0] v);
        begin
            if (v > 32'sd32767)
                clamp_s16 = 16'sd32767;
            else if (v < -32'sd32768)
                clamp_s16 = -16'sd32768;
            else
                clamp_s16 = v[SAMPLE_W-1:0];
        end
    endfunction

endmodule

`default_nettype wire
